"""initial_schema

Revision ID: 8b8fb989bc07
Revises: 
Create Date: 2026-02-22 21:06:06.100242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b8fb989bc07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('bookings', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('bookings', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('idx_bookings_org', table_name='bookings')
    op.drop_index('idx_bookings_time', table_name='bookings')
    op.drop_index('idx_bookings_user', table_name='bookings')
    op.drop_index('idx_bookings_zone', table_name='bookings')
    op.create_index(op.f('ix_bookings_organization_id'), 'bookings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookings_zone_id'), 'bookings', ['zone_id'], unique=False)
    op.drop_constraint('bookings_organization_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_zone_id_fkey', 'bookings', type_='foreignkey')
    op.drop_constraint('bookings_user_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'zones', ['zone_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    op.alter_column('documents', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('documents', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('documents', 'approval_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'approved'::character varying"))
    op.drop_index('idx_documents_approval', table_name='documents')
    op.drop_index('idx_documents_org', table_name='documents')
    op.drop_index('idx_documents_uploader', table_name='documents')
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.drop_constraint('documents_organization_id_fkey', 'documents', type_='foreignkey')
    op.drop_constraint('documents_approved_by_id_fkey', 'documents', type_='foreignkey')
    op.drop_constraint('documents_uploaded_by_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['approved_by_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by_id'], ['id'])
    op.drop_index('idx_incident_comments_incident', table_name='incident_comments')
    op.create_index(op.f('ix_incident_comments_incident_id'), 'incident_comments', ['incident_id'], unique=False)
    op.drop_constraint('incident_comments_author_id_fkey', 'incident_comments', type_='foreignkey')
    op.create_foreign_key(None, 'incident_comments', 'users', ['author_id'], ['id'])
    op.alter_column('incidents', 'priority',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentpriority'),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('incidents', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='incidentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('incidents', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_incidents_assigned', table_name='incidents')
    op.drop_index('idx_incidents_org', table_name='incidents')
    op.drop_index('idx_incidents_reporter', table_name='incidents')
    op.drop_index('idx_incidents_status', table_name='incidents')
    op.create_index(op.f('ix_incidents_organization_id'), 'incidents', ['organization_id'], unique=False)
    op.drop_constraint('incidents_reporter_id_fkey', 'incidents', type_='foreignkey')
    op.drop_constraint('incidents_assigned_to_id_fkey', 'incidents', type_='foreignkey')
    op.drop_constraint('incidents_organization_id_fkey', 'incidents', type_='foreignkey')
    op.create_foreign_key(None, 'incidents', 'users', ['assigned_to_id'], ['id'])
    op.create_foreign_key(None, 'incidents', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'incidents', 'users', ['reporter_id'], ['id'])
    op.alter_column('invitations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'USED', 'EXPIRED', name='invitationstatus'),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('invitations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index('idx_invitations_email', table_name='invitations')
    op.drop_index('idx_invitations_org', table_name='invitations')
    op.drop_index('idx_invitations_token', table_name='invitations')
    op.drop_constraint('invitations_token_key', 'invitations', type_='unique')
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_organization_id'), 'invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.drop_constraint('invitations_organization_id_fkey', 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'organizations', ['organization_id'], ['id'])
    op.drop_index('idx_notifications_read', table_name='notifications')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_constraint('organizations_code_key', 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.alter_column('posts', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('idx_posts_author', table_name='posts')
    op.drop_index('idx_posts_created', table_name='posts')
    op.drop_index('idx_posts_org', table_name='posts')
    op.create_index(op.f('ix_posts_organization_id'), 'posts', ['organization_id'], unique=False)
    op.drop_constraint('posts_author_id_fkey', 'posts', type_='foreignkey')
    op.drop_constraint('posts_organization_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.alter_column('user_organizations', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'PRESIDENT', 'NEIGHBOR', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'NEIGHBOR'::character varying"))
    op.alter_column('user_organizations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index('idx_user_orgs_org', table_name='user_organizations')
    op.drop_index('idx_user_orgs_user', table_name='user_organizations')
    op.drop_constraint('user_organizations_user_id_organization_id_key', 'user_organizations', type_='unique')
    op.drop_column('user_organizations', 'id')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'PRESIDENT', 'NEIGHBOR', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'NEIGHBOR'::character varying"))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'avatar_url')
    op.alter_column('zones', 'zone_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'other'::character varying"))
    op.alter_column('zones', 'available_from',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Time(),
               existing_nullable=True,
               existing_server_default=sa.text("'08:00'::character varying"))
    op.alter_column('zones', 'available_until',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Time(),
               existing_nullable=True,
               existing_server_default=sa.text("'22:00'::character varying"))
    op.drop_index('idx_zones_org', table_name='zones')
    op.create_index(op.f('ix_zones_organization_id'), 'zones', ['organization_id'], unique=False)
    op.drop_constraint('zones_organization_id_fkey', 'zones', type_='foreignkey')
    op.create_foreign_key(None, 'zones', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zones', type_='foreignkey')
    op.create_foreign_key('zones_organization_id_fkey', 'zones', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_zones_organization_id'), table_name='zones')
    op.create_index('idx_zones_org', 'zones', ['organization_id'], unique=False)
    op.alter_column('zones', 'available_until',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True,
               existing_server_default=sa.text("'22:00'::character varying"))
    op.alter_column('zones', 'available_from',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True,
               existing_server_default=sa.text("'08:00'::character varying"))
    op.alter_column('zones', 'zone_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'other'::character varying"))
    op.add_column('users', sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'PRESIDENT', 'NEIGHBOR', name='userrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'NEIGHBOR'::character varying"))
    op.add_column('user_organizations', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_organizations_user_id_organization_id_key', 'user_organizations', ['user_id', 'organization_id'])
    op.create_index('idx_user_orgs_user', 'user_organizations', ['user_id'], unique=False)
    op.create_index('idx_user_orgs_org', 'user_organizations', ['organization_id'], unique=False)
    op.alter_column('user_organizations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('user_organizations', 'role',
               existing_type=sa.Enum('ADMIN', 'PRESIDENT', 'NEIGHBOR', name='userrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'NEIGHBOR'::character varying"))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_organization_id_fkey', 'posts', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('posts_author_id_fkey', 'posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_posts_organization_id'), table_name='posts')
    op.create_index('idx_posts_org', 'posts', ['organization_id'], unique=False)
    op.create_index('idx_posts_created', 'posts', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_posts_author', 'posts', ['author_id'], unique=False)
    op.alter_column('posts', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.create_unique_constraint('organizations_code_key', 'organizations', ['code'])
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index('idx_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.create_foreign_key('invitations_organization_id_fkey', 'invitations', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_organization_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.create_unique_constraint('invitations_token_key', 'invitations', ['token'])
    op.create_index('idx_invitations_token', 'invitations', ['token'], unique=False)
    op.create_index('idx_invitations_org', 'invitations', ['organization_id'], unique=False)
    op.create_index('idx_invitations_email', 'invitations', ['email'], unique=False)
    op.alter_column('invitations', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('invitations', 'status',
               existing_type=sa.Enum('PENDING', 'USED', 'EXPIRED', name='invitationstatus'),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.create_foreign_key('incidents_organization_id_fkey', 'incidents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('incidents_assigned_to_id_fkey', 'incidents', 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('incidents_reporter_id_fkey', 'incidents', 'users', ['reporter_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_incidents_organization_id'), table_name='incidents')
    op.create_index('idx_incidents_status', 'incidents', ['status'], unique=False)
    op.create_index('idx_incidents_reporter', 'incidents', ['reporter_id'], unique=False)
    op.create_index('idx_incidents_org', 'incidents', ['organization_id'], unique=False)
    op.create_index('idx_incidents_assigned', 'incidents', ['assigned_to_id'], unique=False)
    op.alter_column('incidents', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('incidents', 'status',
               existing_type=sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='incidentstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'open'::character varying"))
    op.alter_column('incidents', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentpriority'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_constraint(None, 'incident_comments', type_='foreignkey')
    op.create_foreign_key('incident_comments_author_id_fkey', 'incident_comments', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_incident_comments_incident_id'), table_name='incident_comments')
    op.create_index('idx_incident_comments_incident', 'incident_comments', ['incident_id'], unique=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_uploaded_by_id_fkey', 'documents', 'users', ['uploaded_by_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('documents_approved_by_id_fkey', 'documents', 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('documents_organization_id_fkey', 'documents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.create_index('idx_documents_uploader', 'documents', ['uploaded_by_id'], unique=False)
    op.create_index('idx_documents_org', 'documents', ['organization_id'], unique=False)
    op.create_index('idx_documents_approval', 'documents', ['approval_status'], unique=False)
    op.alter_column('documents', 'approval_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'approved'::character varying"))
    op.alter_column('documents', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('documents', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_user_id_fkey', 'bookings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bookings_zone_id_fkey', 'bookings', 'zones', ['zone_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('bookings_organization_id_fkey', 'bookings', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bookings_zone_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_organization_id'), table_name='bookings')
    op.create_index('idx_bookings_zone', 'bookings', ['zone_id'], unique=False)
    op.create_index('idx_bookings_user', 'bookings', ['user_id'], unique=False)
    op.create_index('idx_bookings_time', 'bookings', ['start_time', 'end_time'], unique=False)
    op.create_index('idx_bookings_org', 'bookings', ['organization_id'], unique=False)
    op.alter_column('bookings', 'end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('bookings', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('bookings', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
